name: Deploy [Staging]

on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“ Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: ðŸŒ©ï¸ Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: ðŸ”¨ Build Project
        uses: borales/actions-yarn@v4
        env:
          VITE_APP_BASE_URL: ${{ vars.API_BASE_URL }}
        with:
          cmd: build # will run `yarn build` command

      - name: ðŸš’ Install SSH Key
        uses: benoitchantre/setup-ssh-authentication-action@1.0.0
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ðŸ§¸ Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸš€ Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/ksbtechadmin/
